apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple-operator
  template:
    metadata:
      labels:
        name: simple-operator
    spec:
      serviceAccountName: simple-operator
      containers:
        - name: simple-operator
          # Replace this with the built image name
          image: submod/simple-operator
          command:
          - simple-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "simple-operator"
