apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.name
  name: svcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inference-configmap
- fieldref:
    fieldPath: data.modelBasePath
  name: modelBasePath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inference-configmap
- fieldref:
    fieldPath: data.pvcName
  name: pvcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inference-configmap
- fieldref:
    fieldPath: data.pvcMountPath
  name: pvcMountPath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inference-configmap
- fieldref:
    fieldPath: data.modelName
  name: modelName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inference-configmap
- fieldref:
    fieldPath: data.servingImage
  name: servingImage
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: inference-configmap

configurations:
- params.yaml

configMapGenerator:
- literals:
  name: inference-configmap
